application: python-koans
version: 0
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: templates/stylesheets

- url: /.*
  static_files: templates/index.html
  upload: templates/(.*)
